version: '3.4'

networks:
  dev:
    driver: bridge

services:
  familybudget.api:
    image: ${DOCKER_REGISTRY-}familybudgetapi
    depends_on:
      - "app_db"
    container_name: family-budget-api
    ports:
      - "33686:8080"
    build:
      context: .
      dockerfile: FamilyBudget.Api/Dockerfile
    environment:
      - ConnectionStrings__DbConnection=User ID=postgres;Password=postgres;Server=app_db;Port=5432;Database=FamilyBudget; IntegratedSecurity=true;Pooling=true
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - dev

  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=FamilyBudget
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgres/data
    networks:
      - dev

  #familybudget.app:
  #  image: familybudget-app:latest
  #  container_name: family-budget-app
  #  ports:
  #    - "4200:80"
  #  networks:
  #    - dev

volumes:
  app_data:


  